#vlan_interfaces:

custom_structured_configuration_vlans:
  - id: 55
    name: MCS-VLAN

custom_structured_configuration_vlan_interfaces:
  - name: vlan55
    shutdown: false
    ip_address: 55.55.55.11/24

custom_structured_configuration_ip_routing: true
