#TEST
#
custom_structured_configuration_vlans:
  - id: 55
    name: MCS-VLAN

#vlan_interfaces:
custom_structured_configuration_vlan_interfaces:
  - name: vlan55
    shutdown: false
    ip_address: 55.55.55.3/24
    ip_virtual_router_addresses: 
      - 55.55.55.1/24

custom_structured_configuration_port_channel_interfaces:
  - name: TEST
    switchport:
      mode trunk:
        allowed_vlan: 55
