#vlan_interfaces:

custom_structured_configuration_vlans:
  - id: 55
    name: MCS-VLAN

custom_structured_configuration_vlan_interfaces:
  - name: vlan55
    shutdown: false
    ip_address: 55.55.55.11/24

custom_structured_configuration_ip_routing: true

custom_structured_configuration_static_routes:
  - vrf: default
    destination_address_prefix: 0.0.0.0/0
    gateway: 55.55.55.1
    name: DEFAULT-ROUTE

custom_structured_configuration_cvx:
  shutdown: false
  services:
    mcs:
      redis:
        password: admin
        password_type: 0
      shutdown: false

custom_structured_configuration_management_api_http:
  enable_http: true
  shutdown: false
